version: "3.8"
services:
  my-code-server:
    image: my-code-server:v2
    container_name: my-code-server
    # user: "${UID}:${GID}" # 解决文件权限问题
    environment:
      - PASSWORD=123456789 # 修改你的强密码！
      - TZ=Asia/Shanghai
    volumes:
      - ./coder:/home/coder
      - ./coder/config/code-server:/root/.config/code-server # root用户读取的配置（含TLS证书）
      - ./coder/.claude:/root/.claude
      - ./workspaces:/opt/workspaces
      - C:/E/workspaces/:/home/coder/workspaces
    ports:
      - "8080:8080"
    #   - "3000:3000"
    restart: unless-stopped

  # caddy:
  #   image: caddy:2
  #   container_name: caddy-proxy
  #   ports:
  #     - "8091:8091"   # 对外依然使用 8091，但现在是 HTTPS
  #   volumes:
  #     - C:/E/workspaces/coderserver/Caddyfile/Caddyfile:/etc/caddy/Caddyfile
  #     - C:/E/workspaces/coderserver/Caddyfile/data:/data
  #   restart: unless-stopped